# Generated by Django 5.0.3 on 2024-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sneakers',
            options={'verbose_name': 'Sneaker', 'verbose_name_plural': 'Sneakers'},
        ),
        migrations.AddField(
            model_name='sneakers',
            name='image',
            field=models.ImageField(default='image', upload_to='C:/Users/vladi/Documents/Python Scripts/Django/study/main/static/main/images/sneakers'),
            preserve_default=False,
        ),
    ]
