# Generated by Django 5.0.3 on 2024-03-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0002_alter_sneakers_options_sneakers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='image',
            field=models.ImageField(upload_to='main/images/sneakers/'),
        ),
    ]
